// GregTech production for the ALLOWED SecurityCraft items. All SecurityCraft recipes are
// disabled in cleanup/securitycraft.js; this re-adds ONLY the permitted subset, each built in
// the ASSEMBLER and self-contained from GT/vanilla materials (the reinforced/"hardened" blocks
// and every other SC intermediate stay uncraftable). Everything is LV-accessible except the
// codebreaker (EV). Each recipe carries a UNIQUE programmed-circuit selector (1..29) so none
// collide — in particular the five otherwise-identical keycards.
//
// Requested tweaks honoured:
//   • denylist (blacklist) module -> uses redstone, NOT an ink sac ("squid sack")
//   • keycard holder             -> leather + steel
//   • motion activated light     -> GT lv_sensor + GT lamp
//   • laser block                -> GT lv_emitter;  camera/detector/scanners -> GT lv_sensor
//   • keypad / keypad door/trap  -> a normal (stone) button
// NOT included: "key panel" (securitycraft:key_panel) has NO obtainable item form in
// SecurityCraft v1.10.2.1 — no item model, no recipe, empty loot table — so it cannot be a
// recipe output. Ask if a later SC version makes it a real item and it can be added.

ServerEvents.recipes(event => {
    event.recipes.gtceu.assembler('wf_sc_alarm')
        .itemOutputs('securitycraft:alarm')
        .circuit(1)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:note_block')
        .itemInputs('2x minecraft:glass')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_whitelist_module')
        .itemOutputs('securitycraft:whitelist_module')
        .circuit(2)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:iron_plate')
        .itemInputs('2x minecraft:paper')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_blacklist_module')
        .itemOutputs('securitycraft:blacklist_module')
        .circuit(3)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:iron_plate')
        .itemInputs('1x minecraft:paper')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_block_change_detector')
        .itemOutputs('securitycraft:block_change_detector')
        .circuit(4)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:redstone_torch')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_security_camera')
        .itemOutputs('securitycraft:security_camera')
        .circuit(5)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:iron_plate')
        .itemInputs('2x minecraft:glass')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_camera_monitor')
        .itemOutputs('securitycraft:camera_monitor')
        .circuit(6)
        .EUt(32)
        .duration(200)
        .itemInputs('6x gtceu:iron_plate')
        .itemInputs('1x minecraft:glass_pane')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_codebreaker')
        .itemOutputs('securitycraft:codebreaker')
        .circuit(7)
        .EUt(2048)
        .duration(600)
        .itemInputs('2x minecraft:diamond')
        .itemInputs('1x minecraft:nether_star')
        .itemInputs('4x minecraft:gold_ingot')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/ev')

    event.recipes.gtceu.assembler('wf_sc_inventory_scanner')
        .itemOutputs('securitycraft:inventory_scanner')
        .circuit(8)
        .EUt(32)
        .duration(300)
        .itemInputs('6x gtceu:steel_plate')
        .itemInputs('2x minecraft:glass')
        .itemInputs('1x minecraft:hopper')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_holder')
        .itemOutputs('securitycraft:keycard_holder')
        .circuit(9)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('2x minecraft:leather')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lock')
        .itemOutputs('securitycraft:keycard_lock')
        .circuit(10)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_reader')
        .itemOutputs('securitycraft:keycard_reader')
        .circuit(11)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:hopper')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lv1')
        .itemOutputs('securitycraft:keycard_lv1')
        .circuit(12)
        .EUt(32)
        .duration(100)
        .itemInputs('2x gtceu:iron_plate')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lv2')
        .itemOutputs('securitycraft:keycard_lv2')
        .circuit(13)
        .EUt(32)
        .duration(100)
        .itemInputs('2x gtceu:iron_plate')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lv3')
        .itemOutputs('securitycraft:keycard_lv3')
        .circuit(14)
        .EUt(32)
        .duration(100)
        .itemInputs('2x gtceu:iron_plate')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lv4')
        .itemOutputs('securitycraft:keycard_lv4')
        .circuit(15)
        .EUt(32)
        .duration(100)
        .itemInputs('2x gtceu:iron_plate')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keycard_lv5')
        .itemOutputs('securitycraft:keycard_lv5')
        .circuit(16)
        .EUt(32)
        .duration(100)
        .itemInputs('2x gtceu:iron_plate')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keypad')
        .itemOutputs('securitycraft:keypad')
        .circuit(17)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:stone_button')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keypad_door_item')
        .itemOutputs('securitycraft:keypad_door_item')
        .circuit(18)
        .EUt(32)
        .duration(300)
        .itemInputs('6x gtceu:steel_plate')
        .itemInputs('1x minecraft:stone_button')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_keypad_trapdoor')
        .itemOutputs('securitycraft:keypad_trapdoor')
        .circuit(19)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:stone_button')
        .itemInputs('1x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_laser_block')
        .itemOutputs('securitycraft:laser_block')
        .circuit(20)
        .EUt(32)
        .duration(300)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('4x minecraft:glass_pane')
        .itemInputs('1x minecraft:redstone_block')
        .itemInputs('1x gtceu:lv_emitter')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_motion_activated_light')
        .itemOutputs('securitycraft:motion_activated_light')
        .circuit(21)
        .EUt(32)
        .duration(200)
        .itemInputs('2x gtceu:steel_plate')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x gtceu:white_lamp')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_door_indestructible_iron_item')
        .itemOutputs('securitycraft:door_indestructible_iron_item')
        .circuit(22)
        .EUt(32)
        .duration(300)
        .itemInputs('6x gtceu:steel_plate')
        .itemInputs('2x minecraft:iron_ingot')

    event.recipes.gtceu.assembler('wf_sc_reinforced_iron_trapdoor')
        .itemOutputs('securitycraft:reinforced_iron_trapdoor')
        .circuit(23)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:iron_ingot')

    event.recipes.gtceu.assembler('wf_sc_retinal_scanner')
        .itemOutputs('securitycraft:retinal_scanner')
        .circuit(24)
        .EUt(32)
        .duration(300)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:ender_eye')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_scanner_door_item')
        .itemOutputs('securitycraft:scanner_door_item')
        .circuit(25)
        .EUt(32)
        .duration(300)
        .itemInputs('6x gtceu:steel_plate')
        .itemInputs('1x minecraft:ender_eye')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_scanner_trapdoor')
        .itemOutputs('securitycraft:scanner_trapdoor')
        .circuit(26)
        .EUt(32)
        .duration(300)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:ender_eye')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_secure_redstone_interface')
        .itemOutputs('securitycraft:secure_redstone_interface')
        .circuit(27)
        .EUt(32)
        .duration(300)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:comparator')
        .itemInputs('1x minecraft:redstone_torch')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_secure_trading_station')
        .itemOutputs('securitycraft:secure_trading_station')
        .circuit(28)
        .EUt(32)
        .duration(300)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('4x minecraft:glass')
        .itemInputs('1x minecraft:hopper')
        .itemInputs('1x minecraft:emerald')
        .itemInputs('1x #gtceu:circuits/lv')

    event.recipes.gtceu.assembler('wf_sc_username_logger')
        .itemOutputs('securitycraft:username_logger')
        .circuit(29)
        .EUt(32)
        .duration(200)
        .itemInputs('4x gtceu:steel_plate')
        .itemInputs('1x minecraft:paper')
        .itemInputs('2x minecraft:redstone')
        .itemInputs('1x gtceu:lv_sensor')
        .itemInputs('1x #gtceu:circuits/lv')
})
