// SecurityCraft blast-resistance override — wfcore WFBlocks / WFBlockResistances (startup binding).
// Every SecurityCraft block -> 60 (hardened & blast-tough; also earns wfcore's golden ">30" tooltip),
// EXCEPT the security camera -> 6 (vanilla cobblestone), so a camera stays easy to knock out.
//
// The id list was captured from "[1.20.1] SecurityCraft v1.10.2.1.jar" (assets/.../blockstates/).
// If SecurityCraft is updated and blocks are added/renamed, regenerate this list. Ids that no longer
// resolve are safely skipped (wfcore logs a warning, no crash). Applied once after all blocks register.
const SC_BLOCK_RESISTANCE  = 60
const SC_CAMERA_RESISTANCE = 6            // vanilla cobblestone blast resistance
const SC_CAMERA_BLOCKS = ['security_camera']

const SC_BLOCKS = [
    'alarm', 'ancient_debris_mine', 'blast_furnace_mine', 'block_change_detector', 'block_pocket_manager',
    'block_pocket_wall', 'bouncing_betty', 'cage_trap', 'chiseled_crystal_quartz', 'claymore',
    'coal_mine', 'cobbled_deepslate_mine', 'cobblestone_mine', 'copper_mine', 'crystal_quartz',
    'crystal_quartz_bricks', 'crystal_quartz_pillar', 'crystal_quartz_slab', 'crystal_quartz_stairs', 'deepslate_coal_mine',
    'deepslate_copper_mine', 'deepslate_diamond_mine', 'deepslate_emerald_mine', 'deepslate_gold_mine', 'deepslate_iron_mine',
    'deepslate_lapis_mine', 'deepslate_mine', 'deepslate_redstone_mine', 'diamond_mine', 'dirt_mine',
    'display_case', 'electrified_iron_fence', 'emerald_mine', 'end_stone_mine', 'fake_lava_block',
    'fake_water_block', 'floor_trap', 'furnace_mine', 'gilded_blackstone_mine', 'glow_display_case',
    'gold_mine', 'gravel_mine', 'horizontal_reinforced_iron_bars', 'ims', 'inventory_scanner',
    'inventory_scanner_field', 'iron_door_reinforced', 'iron_mine', 'keycard_lock', 'keycard_reader',
    'keypad', 'keypad_barrel', 'keypad_blast_furnace', 'keypad_chest', 'keypad_door',
    'keypad_frame', 'keypad_furnace', 'keypad_smoker', 'keypad_trapdoor', 'key_panel',
    'lapis_mine', 'laser', 'laser_block', 'mine', 'motion_activated_light',
    'nether_gold_mine', 'netherrack_mine', 'panic_button', 'portable_radar', 'projector',
    'protecto', 'quartz_mine', 'redstone_mine', 'reinforced_acacia_button', 'reinforced_acacia_fence',
    'reinforced_acacia_fence_gate', 'reinforced_acacia_log', 'reinforced_acacia_planks', 'reinforced_acacia_pressure_plate', 'reinforced_acacia_slab',
    'reinforced_acacia_stairs', 'reinforced_acacia_wood', 'reinforced_amethyst_block', 'reinforced_andesite', 'reinforced_andesite_slab',
    'reinforced_andesite_stairs', 'reinforced_andesite_wall', 'reinforced_bamboo_block', 'reinforced_bamboo_button', 'reinforced_bamboo_fence',
    'reinforced_bamboo_fence_gate', 'reinforced_bamboo_mosaic', 'reinforced_bamboo_mosaic_slab', 'reinforced_bamboo_mosaic_stairs', 'reinforced_bamboo_planks',
    'reinforced_bamboo_pressure_plate', 'reinforced_bamboo_slab', 'reinforced_bamboo_stairs', 'reinforced_basalt', 'reinforced_birch_button',
    'reinforced_birch_fence', 'reinforced_birch_fence_gate', 'reinforced_birch_log', 'reinforced_birch_planks', 'reinforced_birch_pressure_plate',
    'reinforced_birch_slab', 'reinforced_birch_stairs', 'reinforced_birch_wood', 'reinforced_black_carpet', 'reinforced_black_concrete',
    'reinforced_black_glazed_terracotta', 'reinforced_black_stained_glass', 'reinforced_black_stained_glass_pane', 'reinforced_blackstone', 'reinforced_blackstone_slab',
    'reinforced_blackstone_stairs', 'reinforced_blackstone_wall', 'reinforced_black_terracotta', 'reinforced_black_wool', 'reinforced_blue_carpet',
    'reinforced_blue_concrete', 'reinforced_blue_glazed_terracotta', 'reinforced_blue_ice', 'reinforced_blue_stained_glass', 'reinforced_blue_stained_glass_pane',
    'reinforced_blue_terracotta', 'reinforced_blue_wool', 'reinforced_bone_block', 'reinforced_bookshelf', 'reinforced_bricks',
    'reinforced_brick_slab', 'reinforced_brick_stairs', 'reinforced_brick_wall', 'reinforced_brown_carpet', 'reinforced_brown_concrete',
    'reinforced_brown_glazed_terracotta', 'reinforced_brown_stained_glass', 'reinforced_brown_stained_glass_pane', 'reinforced_brown_terracotta', 'reinforced_brown_wool',
    'reinforced_calcite', 'reinforced_cauldron', 'reinforced_chain', 'reinforced_cherry_button', 'reinforced_cherry_fence',
    'reinforced_cherry_fence_gate', 'reinforced_cherry_log', 'reinforced_cherry_planks', 'reinforced_cherry_pressure_plate', 'reinforced_cherry_slab',
    'reinforced_cherry_stairs', 'reinforced_cherry_wood', 'reinforced_chiseled_bookshelf', 'reinforced_chiseled_crystal_quartz_block', 'reinforced_chiseled_deepslate',
    'reinforced_chiseled_nether_bricks', 'reinforced_chiseled_polished_blackstone', 'reinforced_chiseled_quartz_block', 'reinforced_chiseled_red_sandstone', 'reinforced_chiseled_sandstone',
    'reinforced_chiseled_stone_bricks', 'reinforced_clay', 'reinforced_coal_block', 'reinforced_coarse_dirt', 'reinforced_cobbled_deepslate',
    'reinforced_cobbled_deepslate_slab', 'reinforced_cobbled_deepslate_stairs', 'reinforced_cobbled_deepslate_wall', 'reinforced_cobblestone', 'reinforced_cobblestone_slab',
    'reinforced_cobblestone_stairs', 'reinforced_cobblestone_wall', 'reinforced_cobweb', 'reinforced_copper_block', 'reinforced_cracked_deepslate_bricks',
    'reinforced_cracked_deepslate_tiles', 'reinforced_cracked_nether_bricks', 'reinforced_cracked_polished_blackstone_bricks', 'reinforced_cracked_stone_bricks', 'reinforced_crimson_button',
    'reinforced_crimson_fence', 'reinforced_crimson_fence_gate', 'reinforced_crimson_hyphae', 'reinforced_crimson_nylium', 'reinforced_crimson_planks',
    'reinforced_crimson_pressure_plate', 'reinforced_crimson_slab', 'reinforced_crimson_stairs', 'reinforced_crimson_stem', 'reinforced_crying_obsidian',
    'reinforced_crystal_quartz_block', 'reinforced_crystal_quartz_bricks', 'reinforced_crystal_quartz_pillar', 'reinforced_crystal_quartz_slab', 'reinforced_crystal_quartz_stairs',
    'reinforced_cut_copper', 'reinforced_cut_copper_slab', 'reinforced_cut_copper_stairs', 'reinforced_cut_red_sandstone', 'reinforced_cut_red_sandstone_slab',
    'reinforced_cut_sandstone', 'reinforced_cut_sandstone_slab', 'reinforced_cyan_carpet', 'reinforced_cyan_concrete', 'reinforced_cyan_glazed_terracotta',
    'reinforced_cyan_stained_glass', 'reinforced_cyan_stained_glass_pane', 'reinforced_cyan_terracotta', 'reinforced_cyan_wool', 'reinforced_dark_oak_button',
    'reinforced_dark_oak_fence', 'reinforced_dark_oak_fence_gate', 'reinforced_dark_oak_log', 'reinforced_dark_oak_planks', 'reinforced_dark_oak_pressure_plate',
    'reinforced_dark_oak_slab', 'reinforced_dark_oak_stairs', 'reinforced_dark_oak_wood', 'reinforced_dark_prismarine', 'reinforced_dark_prismarine_slab',
    'reinforced_dark_prismarine_stairs', 'reinforced_deepslate', 'reinforced_deepslate_bricks', 'reinforced_deepslate_brick_slab', 'reinforced_deepslate_brick_stairs',
    'reinforced_deepslate_brick_wall', 'reinforced_deepslate_tiles', 'reinforced_deepslate_tile_slab', 'reinforced_deepslate_tile_stairs', 'reinforced_deepslate_tile_wall',
    'reinforced_diamond_block', 'reinforced_diorite', 'reinforced_diorite_slab', 'reinforced_diorite_stairs', 'reinforced_diorite_wall',
    'reinforced_dirt', 'reinforced_dispenser', 'reinforced_dripstone_block', 'reinforced_dropper', 'reinforced_emerald_block',
    'reinforced_end_rod', 'reinforced_end_stone', 'reinforced_end_stone_bricks', 'reinforced_end_stone_brick_slab', 'reinforced_end_stone_brick_stairs',
    'reinforced_end_stone_brick_wall', 'reinforced_exposed_copper', 'reinforced_exposed_cut_copper', 'reinforced_exposed_cut_copper_slab', 'reinforced_exposed_cut_copper_stairs',
    'reinforced_fence_gate', 'reinforced_glass', 'reinforced_glass_pane', 'reinforced_glowstone', 'reinforced_gold_block',
    'reinforced_granite', 'reinforced_granite_slab', 'reinforced_granite_stairs', 'reinforced_granite_wall', 'reinforced_grass_block',
    'reinforced_grass_path', 'reinforced_gravel', 'reinforced_gray_carpet', 'reinforced_gray_concrete', 'reinforced_gray_glazed_terracotta',
    'reinforced_gray_stained_glass', 'reinforced_gray_stained_glass_pane', 'reinforced_gray_terracotta', 'reinforced_gray_wool', 'reinforced_green_carpet',
    'reinforced_green_concrete', 'reinforced_green_glazed_terracotta', 'reinforced_green_stained_glass', 'reinforced_green_stained_glass_pane', 'reinforced_green_terracotta',
    'reinforced_green_wool', 'reinforced_hardened_clay', 'reinforced_hopper', 'reinforced_ice', 'reinforced_iron_bars',
    'reinforced_iron_block', 'reinforced_iron_trapdoor', 'reinforced_jungle_button', 'reinforced_jungle_fence', 'reinforced_jungle_fence_gate',
    'reinforced_jungle_log', 'reinforced_jungle_planks', 'reinforced_jungle_pressure_plate', 'reinforced_jungle_slab', 'reinforced_jungle_stairs',
    'reinforced_jungle_wood', 'reinforced_ladder', 'reinforced_lantern', 'reinforced_lapis_block', 'reinforced_lava_cauldron',
    'reinforced_lectern', 'reinforced_lever', 'reinforced_light_blue_carpet', 'reinforced_light_blue_concrete', 'reinforced_light_blue_glazed_terracotta',
    'reinforced_light_blue_stained_glass', 'reinforced_light_blue_stained_glass_pane', 'reinforced_light_blue_terracotta', 'reinforced_light_blue_wool', 'reinforced_light_gray_carpet',
    'reinforced_light_gray_concrete', 'reinforced_light_gray_glazed_terracotta', 'reinforced_light_gray_stained_glass', 'reinforced_light_gray_stained_glass_pane', 'reinforced_light_gray_terracotta',
    'reinforced_light_gray_wool', 'reinforced_lime_carpet', 'reinforced_lime_concrete', 'reinforced_lime_glazed_terracotta', 'reinforced_lime_stained_glass',
    'reinforced_lime_stained_glass_pane', 'reinforced_lime_terracotta', 'reinforced_lime_wool', 'reinforced_magenta_carpet', 'reinforced_magenta_concrete',
    'reinforced_magenta_glazed_terracotta', 'reinforced_magenta_stained_glass', 'reinforced_magenta_stained_glass_pane', 'reinforced_magenta_terracotta', 'reinforced_magenta_wool',
    'reinforced_magma_block', 'reinforced_mangrove_button', 'reinforced_mangrove_fence', 'reinforced_mangrove_fence_gate', 'reinforced_mangrove_log',
    'reinforced_mangrove_planks', 'reinforced_mangrove_pressure_plate', 'reinforced_mangrove_slab', 'reinforced_mangrove_stairs', 'reinforced_mangrove_wood',
    'reinforced_moss_block', 'reinforced_moss_carpet', 'reinforced_mossy_cobblestone', 'reinforced_mossy_cobblestone_slab', 'reinforced_mossy_cobblestone_stairs',
    'reinforced_mossy_cobblestone_wall', 'reinforced_mossy_stone_bricks', 'reinforced_mossy_stone_brick_slab', 'reinforced_mossy_stone_brick_stairs', 'reinforced_mossy_stone_brick_wall',
    'reinforced_moving_piston', 'reinforced_mud', 'reinforced_mud_bricks', 'reinforced_mud_brick_slab', 'reinforced_mud_brick_stairs',
    'reinforced_mud_brick_wall', 'reinforced_mycelium', 'reinforced_nether_brick_fence', 'reinforced_nether_bricks', 'reinforced_nether_brick_slab',
    'reinforced_nether_brick_stairs', 'reinforced_nether_brick_wall', 'reinforced_netherite_block', 'reinforced_netherrack', 'reinforced_nether_wart_block',
    'reinforced_normal_stone_slab', 'reinforced_oak_button', 'reinforced_oak_fence', 'reinforced_oak_fence_gate', 'reinforced_oak_log',
    'reinforced_oak_planks', 'reinforced_oak_pressure_plate', 'reinforced_oak_slab', 'reinforced_oak_stairs', 'reinforced_oak_wood',
    'reinforced_observer', 'reinforced_obsidian', 'reinforced_ochre_froglight', 'reinforced_orange_carpet', 'reinforced_orange_concrete',
    'reinforced_orange_glazed_terracotta', 'reinforced_orange_stained_glass', 'reinforced_orange_stained_glass_pane', 'reinforced_orange_terracotta', 'reinforced_orange_wool',
    'reinforced_oxidized_copper', 'reinforced_oxidized_cut_copper', 'reinforced_oxidized_cut_copper_slab', 'reinforced_oxidized_cut_copper_stairs', 'reinforced_packed_ice',
    'reinforced_packed_mud', 'reinforced_pearlescent_froglight', 'reinforced_pink_carpet', 'reinforced_pink_concrete', 'reinforced_pink_glazed_terracotta',
    'reinforced_pink_stained_glass', 'reinforced_pink_stained_glass_pane', 'reinforced_pink_terracotta', 'reinforced_pink_wool', 'reinforced_piston',
    'reinforced_piston_head', 'reinforced_podzol', 'reinforced_polished_andesite', 'reinforced_polished_andesite_slab', 'reinforced_polished_andesite_stairs',
    'reinforced_polished_basalt', 'reinforced_polished_blackstone', 'reinforced_polished_blackstone_bricks', 'reinforced_polished_blackstone_brick_slab', 'reinforced_polished_blackstone_brick_stairs',
    'reinforced_polished_blackstone_brick_wall', 'reinforced_polished_blackstone_button', 'reinforced_polished_blackstone_pressure_plate', 'reinforced_polished_blackstone_slab', 'reinforced_polished_blackstone_stairs',
    'reinforced_polished_blackstone_wall', 'reinforced_polished_deepslate', 'reinforced_polished_deepslate_slab', 'reinforced_polished_deepslate_stairs', 'reinforced_polished_deepslate_wall',
    'reinforced_polished_diorite', 'reinforced_polished_diorite_slab', 'reinforced_polished_diorite_stairs', 'reinforced_polished_granite', 'reinforced_polished_granite_slab',
    'reinforced_polished_granite_stairs', 'reinforced_powder_snow_cauldron', 'reinforced_prismarine', 'reinforced_prismarine_bricks', 'reinforced_prismarine_brick_slab',
    'reinforced_prismarine_brick_stairs', 'reinforced_prismarine_slab', 'reinforced_prismarine_stairs', 'reinforced_prismarine_wall', 'reinforced_purple_carpet',
    'reinforced_purple_concrete', 'reinforced_purple_glazed_terracotta', 'reinforced_purple_stained_glass', 'reinforced_purple_stained_glass_pane', 'reinforced_purple_terracotta',
    'reinforced_purple_wool', 'reinforced_purpur_block', 'reinforced_purpur_pillar', 'reinforced_purpur_slab', 'reinforced_purpur_stairs',
    'reinforced_quartz_block', 'reinforced_quartz_bricks', 'reinforced_quartz_pillar', 'reinforced_quartz_slab', 'reinforced_quartz_stairs',
    'reinforced_raw_copper_block', 'reinforced_raw_gold_block', 'reinforced_raw_iron_block', 'reinforced_red_carpet', 'reinforced_red_concrete',
    'reinforced_red_glazed_terracotta', 'reinforced_red_nether_bricks', 'reinforced_red_nether_brick_slab', 'reinforced_red_nether_brick_stairs', 'reinforced_red_nether_brick_wall',
    'reinforced_red_sand', 'reinforced_red_sandstone', 'reinforced_red_sandstone_slab', 'reinforced_red_sandstone_stairs', 'reinforced_red_sandstone_wall',
    'reinforced_red_stained_glass', 'reinforced_red_stained_glass_pane', 'reinforced_redstone_block', 'reinforced_redstone_lamp', 'reinforced_red_terracotta',
    'reinforced_red_wool', 'reinforced_rooted_dirt', 'reinforced_sand', 'reinforced_sandstone', 'reinforced_sandstone_slab',
    'reinforced_sandstone_stairs', 'reinforced_sandstone_wall', 'reinforced_scaffolding', 'reinforced_sea_lantern', 'reinforced_shroomlight',
    'reinforced_smooth_basalt', 'reinforced_smooth_crystal_quartz', 'reinforced_smooth_crystal_quartz_slab', 'reinforced_smooth_crystal_quartz_stairs', 'reinforced_smooth_quartz',
    'reinforced_smooth_quartz_slab', 'reinforced_smooth_quartz_stairs', 'reinforced_smooth_red_sandstone', 'reinforced_smooth_red_sandstone_slab', 'reinforced_smooth_red_sandstone_stairs',
    'reinforced_smooth_sandstone', 'reinforced_smooth_sandstone_slab', 'reinforced_smooth_sandstone_stairs', 'reinforced_smooth_stone', 'reinforced_snow_block',
    'reinforced_soul_lantern', 'reinforced_soul_sand', 'reinforced_soul_soil', 'reinforced_spruce_button', 'reinforced_spruce_fence',
    'reinforced_spruce_fence_gate', 'reinforced_spruce_log', 'reinforced_spruce_planks', 'reinforced_spruce_pressure_plate', 'reinforced_spruce_slab',
    'reinforced_spruce_stairs', 'reinforced_spruce_wood', 'reinforced_sticky_piston', 'reinforced_stone', 'reinforced_stone_bricks',
    'reinforced_stone_brick_slab', 'reinforced_stone_brick_stairs', 'reinforced_stone_brick_wall', 'reinforced_stone_button', 'reinforced_stone_polished_andesite',
    'reinforced_stone_polished_granite', 'reinforced_stone_pressure_plate', 'reinforced_stone_slab', 'reinforced_stone_stairs', 'reinforced_stripped_acacia_log',
    'reinforced_stripped_acacia_wood', 'reinforced_stripped_bamboo_block', 'reinforced_stripped_birch_log', 'reinforced_stripped_birch_wood', 'reinforced_stripped_cherry_log',
    'reinforced_stripped_cherry_wood', 'reinforced_stripped_crimson_hyphae', 'reinforced_stripped_crimson_stem', 'reinforced_stripped_dark_oak_log', 'reinforced_stripped_dark_oak_wood',
    'reinforced_stripped_jungle_log', 'reinforced_stripped_jungle_wood', 'reinforced_stripped_mangrove_log', 'reinforced_stripped_mangrove_wood', 'reinforced_stripped_oak_log',
    'reinforced_stripped_oak_wood', 'reinforced_stripped_spruce_log', 'reinforced_stripped_spruce_wood', 'reinforced_stripped_warped_hyphae', 'reinforced_stripped_warped_stem',
    'reinforced_tinted_glass', 'reinforced_tuff', 'reinforced_verdant_froglight', 'reinforced_warped_button', 'reinforced_warped_fence',
    'reinforced_warped_fence_gate', 'reinforced_warped_hyphae', 'reinforced_warped_nylium', 'reinforced_warped_planks', 'reinforced_warped_pressure_plate',
    'reinforced_warped_slab', 'reinforced_warped_stairs', 'reinforced_warped_stem', 'reinforced_warped_wart_block', 'reinforced_water_cauldron',
    'reinforced_weathered_copper', 'reinforced_weathered_cut_copper', 'reinforced_weathered_cut_copper_slab', 'reinforced_weathered_cut_copper_stairs', 'reinforced_white_carpet',
    'reinforced_white_concrete', 'reinforced_white_glazed_terracotta', 'reinforced_white_stained_glass', 'reinforced_white_stained_glass_pane', 'reinforced_white_terracotta',
    'reinforced_white_wool', 'reinforced_yellow_carpet', 'reinforced_yellow_concrete', 'reinforced_yellow_glazed_terracotta', 'reinforced_yellow_stained_glass',
    'reinforced_yellow_stained_glass_pane', 'reinforced_yellow_terracotta', 'reinforced_yellow_wool', 'retinal_scanner', 'rift_stabilizer',
    'sand_mine', 'scanner_door', 'scanner_trapdoor', 'secret_acacia_hanging_sign', 'secret_acacia_sign_standing',
    'secret_acacia_sign_wall', 'secret_acacia_wall_hanging_sign', 'secret_bamboo_hanging_sign', 'secret_bamboo_sign_standing', 'secret_bamboo_sign_wall',
    'secret_bamboo_wall_hanging_sign', 'secret_birch_hanging_sign', 'secret_birch_sign_standing', 'secret_birch_sign_wall', 'secret_birch_wall_hanging_sign',
    'secret_cherry_hanging_sign', 'secret_cherry_sign_standing', 'secret_cherry_sign_wall', 'secret_cherry_wall_hanging_sign', 'secret_crimson_hanging_sign',
    'secret_crimson_sign_standing', 'secret_crimson_sign_wall', 'secret_crimson_wall_hanging_sign', 'secret_dark_oak_hanging_sign', 'secret_dark_oak_sign_standing',
    'secret_dark_oak_sign_wall', 'secret_dark_oak_wall_hanging_sign', 'secret_jungle_hanging_sign', 'secret_jungle_sign_standing', 'secret_jungle_sign_wall',
    'secret_jungle_wall_hanging_sign', 'secret_mangrove_hanging_sign', 'secret_mangrove_sign_standing', 'secret_mangrove_sign_wall', 'secret_mangrove_wall_hanging_sign',
    'secret_oak_hanging_sign', 'secret_oak_wall_hanging_sign', 'secret_sign_standing', 'secret_sign_wall', 'secret_spruce_hanging_sign',
    'secret_spruce_sign_standing', 'secret_spruce_sign_wall', 'secret_spruce_wall_hanging_sign', 'secret_warped_hanging_sign', 'secret_warped_sign_standing',
    'secret_warped_sign_wall', 'secret_warped_wall_hanging_sign', 'secure_redstone_interface', 'secure_trading_station', 'security_camera',
    'sentry_disguise', 'smoker_mine', 'smooth_crystal_quartz', 'smooth_crystal_quartz_slab', 'smooth_crystal_quartz_stairs',
    'sonic_security_system', 'stone_mine', 'suspicious_gravel_mine', 'suspicious_sand_mine', 'track_mine',
    'trophy_system', 'username_logger',
]

SC_BLOCKS.forEach(id => {
    const res = SC_CAMERA_BLOCKS.indexOf(id) >= 0 ? SC_CAMERA_RESISTANCE : SC_BLOCK_RESISTANCE
    WFBlocks.setResistance('securitycraft:' + id, res)
})
